apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "fb-submitter-service-monitor-{{ .Values.environmentName }}"
  namespace: "formbuilder-platform-{{ .Values.environmentName }}"
spec:
  selector:
    matchLabels:
      app: "fb-submitter-api-{{ .Values.environmentName }}"
  endpoints:
  - port: http
    interval: 15s
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: "allow-fb-submitter-prometheus-{{ .Values.environmentName }}"
  namespace: "formbuilder-platform-{{ .Values.environmentName }}"
spec:
  podSelector:
    matchLabels:
      app: "fb-submitter-api-{{ .Values.environmentName }}"
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          component: monitoring
